# Generated by Django 2.0.4 on 2018-05-07 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url_video', models.URLField()),
                ('description', models.TextField(help_text='Enter a brief description of the movie', max_length=1000)),
                ('year', models.DateField(blank=True, null=True)),
                ('actors', models.CharField(max_length=100)),
                ('url_image', models.URLField()),
                ('rate', models.IntegerField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Author')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
